config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/about' => 'homes#about', as: 'about'
    root to: 'homes#top'
  end

  namespace :public do
    resources :items, only: [:index,:show]
  end

  namespace :public do
    resources :customers, only: [:update,:edit]
    get 'customers/my_page' => 'customers#show', as: 'customers'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw/:id' => 'customers#withdraw', as: 'withdraw'
  end

  namespace :public do
    resources :cart_items, only: [:index,:update,:destroy,:create]
    delete 'cart_items/destroy_all/:id' => 'cart_items#destroy_all', as: 'destroy_all'
  end

  namespace :public do
    resources :orders, only: [:new,:index,:show,:create]
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/thanks' => 'orders#thanks', as: 'thanks'
  end

  namespace :public do
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only: [:index,:create,:edit,:update]
  end

  namespace :admin do
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

  namespace :admin do
    resources :customers, only: [:index,:create,:edit,:update,:show]
  end

  namespace :admin do
   resources :orders, only: [:show,:update,:index]
   resources :order_details, only: [:update]
  end

  namespace :admin do
    get "homes/top"
  end

  root to: "homes#top"

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer

  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

  def self.cart_items_total_payment(cart_items)
    array = []
    cart_items.each do |cart_item|
      array << cart_item.item.price * cart_item.amount
    end
    return (array.sum * 1.1).floor
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :orders, dependent: :destroy

  validates :name, presence: true


end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details

  validates :is_active, inclusion: {in: [true, false]}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum maiking_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}


end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
		@customer = Customer.find(params[:id])
  end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
		@customer = Customer.find(params[:id])
			if @customer.update(customer_params)
			   flash[:success] = "Customer was successfully updated"
			   redirect_to admin_customer_path
			else
				render "edit"
			end

	end

  private

  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:email,:encrypted_password,:postal_code,:address,:telephone_number,:is_active,:is_delete)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    # binding.pry
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :configure_permitted_parameters, if: :devise_controller?

  # # def after_sign_in_path_for(resource)
  # #   root_path
  # # end



  # # def after_sign_out_path_for(resource)
  # #   root_path
  # # end


  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h1>会員情報編集</h1>

      <%= form_with model: @customer, url: public_customer_path(@customer.id), method: :patch do |f| %>

          <div class="form-group">

          <label for="customer_last_name">Last name</label>

            <%= f.text_field :first_name, class:'form-control item_name'  %>

          </div>

          <div class="form-group">

            <label for="customer_first_name">First name</label>

             <%= f.text_field :first_name, class:'form-control item_introduction' %>

          </div>

          <div class="form-group">

            <label for="customer_last_name_kana">Last name kana</label>

            <%= f.text_field :last_name_kana, class:'form-control item_price' %>

          </div>

          <div class="form-group">

            <label for="customer_first_name_kana">First_name_kana</label>

            <%= f.text_field :first_name_kana, class:'form-control item_price' %>

          </div>

          <div class="form-group">

            <label for="customer_email">Email</label>

            <%= f.text_field :email, class:'form-control item_price' %>

          </div>

          <div class="form-group">

            <label for="customer_postal_code">Postal code</label>

            <%= f.text_field :postal_code, class:'form-control item_price' %>

          </div>

          <div class="form-group">

            <label for="customer_address">Address</label>

            <%= f.text_field :address, class:'form-control item_price' %>

          </div>

          <div class="form-group">

            <label for="customer_telephone_number">Telephone number</label>

            <%= f.text_field :telephone_number, class:'form-control item_price' %>

          </div>

          <div class="form-group">

            <%= f.submit 'Update item', class:'btn btn-success' %>

          </div>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/customers/index.html.erb
<br>
<h1 class="mx-auto col-5 text-center">会員情報</h1>
<br>

<div class="border col-10 mx-auto">

  <hr>
  <br>
  <h2>会員一覧</h2>

  <div class="row">

    <div class="col-md">

      <table class="table">

        <thead class="thead-dark">

          <tr>

            <th scope="col">会員ID</th>

            <th scope="col">氏名</th>

            <th scope="col">メールアドレス</th>

            <th scope="col">ステータス</th>

            <th scope="col"></th>

          </tr>

        </thead>

        <% @customers.each do |customer| %>

          <tbody>

            <tr>

              <td><%= customer.id %></td>

              <td>
                <%= link_to (customer.last_name + customer.first_name),admin_customer_path(customer.id) %>
              </td>

              <td><%= customer.email %></td>

              <td>
                <% if customer.is_deleted %>
                  退会済
                <% else %>
                  有効
                <% end %>
              </td>

              <td class="text-right">

                  <%= link_to "編集", edit_admin_customer_path(customer.id), class:'btn btn-sm btn-success' %>

                  <%= link_to "削除", admin_customers_path(customer.id), class:'btn btn-sm btn-danger', method: :delete %>

              </td>

            </tr>

          </tbody>

        <% end %>

      </table>

     </div>

  </div>
  <br>

</div>

<br>
<br>

app/views/admin/customers/show.html.erb
<br>
<h1 class="mx-auto col-5 text-center">会員情報</h1>
<br>

<div class="border col-10 mx-auto">

  <div class="container">

  <h1><%= (@customer.last_name + @customer.first_name) %>さんの会員詳細</h1>

    <div class="row">

      <div class="col-xs-7">

        <div>
          <p>
          <strong class="col-xs-3">顧客ID</strong><%= @customer.id %>
          <% if @customer.is_deleted %>
            <span class="bg-danger">退会済</span>
          <% else %>
            <span class="bg-primary">有効会員</span>
          <% end %>
          </p>
        </div>
        <br>

        <div>
          <p><strong class="col-xs-3">氏名</strong><%= (@customer.last_name + @customer.first_name) %></p>
        </div>
        <br>

        <div>
          <p><strong class="col-xs-3">カナ</strong><%= (@customer.last_name_kana + @customer.first_name_kana) %></p>
        </div>
        <br>

        <div>
          <p><strong class="col-xs-3">郵便番号</strong><%= @customer.postal_code.to_s.insert(3, "-") %></p>
        </div>
        <br>

        <div>
          <p><strong class="col-xs-3">住所</strong><%= @customer.address %></p>
        </div>
        </br>

        <div>
          <p><strong class="col-xs-3">電話番号</strong><%= @customer.telephone_number %></p>
        </div>
        </br>

        <div>
          <p><strong class="col-xs-3">メールアドレス</strong><%= @customer.email %></p>
        </div>
        </br>

        <span>
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-primary" %>
    	  </span>
    	  <span><%= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-primary" %></span>

      </div>

    </div>

  </div>

</div>