config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/about' => 'homes#about', as: 'about'
    root to: 'homes#top'
  end

  namespace :public do
    resources :items, only: [:index,:show]
  end

  namespace :public do
    resources :customers, only: [:update,:edit]
    get 'customers/my_page' => 'customers#show', as: 'customers'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw/:id' => 'customers#withdraw', as: 'withdraw'
  end

  namespace :public do
    resources :cart_items, only: [:index,:update,:destroy,:create]
    delete 'cart_items/destroy_all/:id' => 'cart_items#destroy_all', as: 'destroy_all'
  end

  namespace :public do
    resources :orders, only: [:new,:index,:show,:create]
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/thanks' => 'orders#thanks', as: 'thanks'
  end

  namespace :public do
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only: [:index,:create,:edit,:update]
  end

  namespace :admin do
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

  namespace :admin do
    resources :customers, only: [:index,:create,:edit,:update,:show]
  end

  namespace :admin do
   resources :orders, only: [:show,:update,:index]
   resources :order_details, only: [:update]
  end

  namespace :admin do
    get "homes/top"
  end

  root to: "homes#top"

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer

  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

  def self.cart_items_total_payment(cart_items)
    array = []
    cart_items.each do |cart_item|
      array << cart_item.item.price * cart_item.amount
    end
    return (array.sum * 1.1).floor
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :orders, dependent: :destroy

  validates :name, presence: true


end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details

  validates :is_active, inclusion: {in: [true, false]}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum maiking_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name, :is_active)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    # binding.pry
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  before_action :authenticate_admin!


  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    @order_details = @order.order_details

    if @order.order_status == "入金確認"
      @order_details.each do |order_detail|
        order_detail.maiking_status = "製作待ち"
        order_detail.save
      end
    end
    redirect_to admin_order_path
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end



#   def show

#   end

#   def update
#     @order = Order.find(params[:id])
#     @order.update(order_params)
#     redirect_to order_path(@order.id)
#   end

#   def order_params
#     params.require(:order).permit(:postal_code,:address,:name,:shipping_cost,:total_payment,:payment_method,:order_status)
#   end

# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :configure_permitted_parameters, if: :devise_controller?

  # # def after_sign_in_path_for(resource)
  # #   root_path
  # # end



  # # def after_sign_out_path_for(resource)
  # #   root_path
  # # end


  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/_genre_errors.html.erb
<% if genre.errors.any? %>
  <%= genre.errors.count %>prohibited this obj from being saved:
  <% genre.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/admin/genres/_genre_index.html.erb
<% genres.each do |genre| %>

  <tr>

    <td><%= genre.name %></td>

    <% if genre.is_active == true %>

    <td>有効</td>

    <% elsif genre.is_active == false %>
      <td>無効</td>
    <% end %>

    <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-primary" %></td>

  </tr>

<% end %>

app/views/admin/genres/_genre_sidebar.html.erb
<table class="genre-table table table-bordered table-hover">

  <thead class="genre-thead">

    <tr>

      <th class="active">ジャンル検索</th>

    </tr>

  </thead>

  <tbody>

    <% genres.each do |genre| %>

      <tr>

        <td>

          <%= link_to products_path(genre_id: genre.id) do %>
            <%= genre.name %>
          <% end %>

        </td>

      </tr>

    <% end %>

  </tbody>

 </table>

app/views/admin/genres/edit.html.erb
<div class="container">

  <div class="row">

    <div class="col-xs-6">

      <h3>ジャンル編集</h3>

      <%= form_with model: @genre, url: admin_genre_path, class: "genre_edit_form", local:true do |f| %>

        <div>
          <%= f.label :ジャンル %>
          <%= f.text_field :name, class: "genre-edit-field" %></td>
          <%= f.radio_button :is_active, :true %>
          <%= f.label :is_active, "有効"%>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "無効"%>
          <%= f.submit "変更を保存する", class: "btn btn-primary genre_edit_btn" %>
        </div>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/genres/index.html.erb
<br>
<br>

<div class="container">

  <div class="row">

    <div class="col-md-6">

      <h3 class="genre-head">ジャンル一覧・追加</h3>

      <%= render 'genre_errors', genre: @genre %>

      <%= form_with model: @genre, url: admin_genres_path do |f| %>

        <div>
          <%= f.label :ジャンル %>
          <%= f.text_field :name %>
          <%= f.submit "追加", class: "btn btn-primary genre_btn" %>
        </div>

      <% end %>

      <table class='table genre-table'>

        <thead>

          <tr>

            <th class="active col-xs-6">ジャンル</th>
            <th class="active col-xs-2">状態</th>
            <th class="active col-xs-3"></th>

          </tr
          >
        </thead>

        <tbody class="genre_area">

          <%= render 'genre_index', genres: @genres %>

        </tbody>

      </table>

    </div>

  </div>

</div>

app/views/admin/items/edit.html.erb
<br>
<div class="border col-10 mx-auto">

<%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>

    <div class="form-group">

    <label for="item_name">Name</label>

      <%= f.text_field :name, class:'form-control item_name'  %>

    </div>

    <div class="form-group">

      <label for="item_introduction">Introduction</label>

       <%= f.text_area :introduction, class:'form-control item_introduction' %>

    </div>

    <div class="form-group">

      <label for="item_price">Price</label>

       <%= f.text_area :price, class:'form-control item_price' %>

    </div>

    <div class="form-group">

      <%= f.submit 'Update item', class:'btn btn-success' %>

    </div>

<% end %>

</div>

app/views/admin/items/index.html.erb
<div class="album py-5 bg-light">

  <div class="container">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

      <div class="d-flex align-items-center justify-content-center">
        <%= link_to new_admin_item_path do %>
          <button type="button" class="btn-outline-dark btn-circle btn-lg">＋</button>
        <% end %>
      </div>

      <% @items.each do |item| %>

        <div class="col">

          <div class="card shadow-sm">

            <%= link_to admin_item_path(item.id) do %>

              <%= image_tag item.image, size: "250x225", class:'bd-placeholder-img card-img-top' %>

            <% end %>

            <div class="card-body">

              <p class="card-title">商品名:<%= item.name %></p>

              <div class="d-flex justify-content-between align-items-center">

                <small class="text-muted">価格:<%= item.price %>円</small>

                <small class="text-muted">
                  <% if item.is_active %>
                    販売中
                  <% else %>
                    <%= "売り切れ" %>
                  <% end %>
                </small>

              </div>

            </div>

          </div>

        </div>

      <% end %>

    </div>

  </div>

</div>

app/views/admin/items/new.html.erb
<div class="container">

  <div class="m-2 text-center">

    <h1 class="h3 mb-2 font-weight-normal">商品登録</h1>

     <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

        <div class="form-group">

          <label for="item_name">Name</label>

          <%= f.text_field :name, class:'form-control item_name' %>

        </div>

        <div class="form-group">

          <label for="item_name">Image</label>

          <%= f.file_field :image, accept: "image/*",  class:'form-control image' %>

        </div>

        <div class="form-group">

          <label for="item_introduction">Introduction</label>

          <%= f.text_area :introduction, class:'form-control item_intorduction' %>

        </div>

        <div class="form-group">

          <label for="item_introduction">Genre</label>

          <%= f.collection_select :genre_id, Genre.all,:id,:name,{promit:"--選択してください--"}, {class:'form-control item_genre'} %>

        </div>


        <div class="form-group">

          <label for="item_price">Price</label>

          <%= f.text_field :price, class:'form-control item_price' %>

        </div>

        <div class="form-group">

          <%= f.submit '商品登録', class:'btn btn-success' %>

        </div>

      <% end %>

  </div>

</div>

app/views/admin/items/show.html.erb
<br>
<div class="container">

  <div class="col d-flex align-items-center">

    <div class="card shadow-sm">

      <%= link_to admin_item_path(@item.id) do %>

        <%= image_tag @item.image, size: "autexaute", class:'bd-placeholder-img card-img-top' %>

      <% end %>

      <div class="card-body">

        <p class="card-title">商品名:<%= @item.name %></p>

        <p class="card-title">ジャンル:<%= @item.genre_id %></p>

        <p class="card-title">紹介:<br><%= @item.introduction %></p>

        <div class="d-flex justify-content-between align-items-center">

          <small class="text-muted">価格:<%= @item.price %>円</small>

          <small class="text-muted">
            <% if @item.is_active %>
              販売中
            <% else %>
              <%= "売り切れ" %>
            <% end %>
          </small>

        </div>

        <div class="text-right">
          <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-primary" %>
        </div>

      </div>

    </div>

  </div>

</div>

<br>
<br>

app/views/admin/orders/index.html.erb
<div class="border col-10 mx-auto">

<hr>
  <br>
  <h2>注文履歴一覧</h2>

  <div class="row">

    <div class="col-md">

      <table class="table">

        <thead class="thead-dark">

          <tr>

            <th scope="col">注文日</th>

            <th scope="col">配送先</th>

            <th scope="col">注文商品</th>

            <th scope="col">支払金額</th>

            <th scope="col">ステータス</th>

            <th scope="col">注文詳細</th>

          </tr>

        </thead>

        <% @orders.each do |order| %>

          <tbody>

            <tr>

              <td><%= order.created_at.to_s(:datetime_jp) %></td>

              <td>
                <%= order.postal_code %><br/>
                <%= order.address %><br/>
                <%= order.name %>
              </td>

              <td>
                <% order.order_details.each do |order_detail| %>
                  <%= order_detail.item.name %>
                <% end %>
              </td>

              <td><%= "#{order.total_payment.to_s(:delimited)}" %>円</td>

              <td><%= order.order_status %></td>

              <td><%= link_to '表示する', admin_order_path(order.id) %></td>

            </tr>

          </tbody>

        <% end %>

      </table>

     </div>

    </div>
    <br>

  </div>

  <br>
  <br>

</div>

app/views/admin/orders/show.html.erb
<br>

<div class="container">

  <h3>注文履歴詳細</h3>

  <div class="border col-10 mx-auto">

  <div class="row">

    <div class="col-xs-6">

      <div>
        <p>
          <strong class="col-xs-2">購入者</strong>
          <%= link_to admin_customer_path(@order) do %>
            <%= @order.customer.last_name %><%= @order.customer.first_name %>
          <% end %>
        </p>
      </div>
      <br>

      <div>
        <p>
          <strong class="col-xs-2">配送先</strong>
          <%= (@order.customer.postal_code).to_s.insert(3, "-") %>
          <%= @order.customer.address %>
        </p>
      </div>
      <br>

      <div>
        <p>
          <strong class="col-xs-2">支払い方法</strong>
          <%= @order.payment_method %>
        </p>
      </div>
      <br>

      <div>

        <p>
          <strong class="col-xs-4">注文ステータス</strong>
          <%= form_with model:@order, url: admin_order_path, local: true do |f| %>
            <%= f.select :order_status, ["入金待ち", "入金確認","製作中","発送準備中","発送済み"] %>
            <%= f.submit "更新", class: 'btn btn-primary' %>
          <% end %>
        </p>

      </div>

    </div>

  </div>

  <div class="row">

    <div class="col-xs-8">

      <table class='order-show-table table'>

        <thead>

          <tr>

            <th class="active">商品名</th>
            <th class="active">単価（税込）</th>
            <th class="active">数量</th>
            <th class="active">小計</th>
            <th class="active">製作ステータス</th>

          <tr>

        </thead>

        <% @order_details.each do |order_detail| %>

        <tbody>

          <tr>

            <td class="col-xs-4"><%= order_detail.item.name%></td>

            <td class="col-xs-2">¥<%= (order_detail.price*1.1).floor.to_s(:delimited) %></td>

            <td><%= order_detail.amount %></td>

            <td class="col-xs-2">¥<%= ((order_detail.price * order_detail.amount*1.1).floor).to_s(:delimited) %></td>

            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local: true do |f| %>
                <%= f.select :maiking_status, ["製作不可", "製作待ち", "製作中", "製作完了"] %>
                <%= f.submit "更新", class: 'btn btn-primary' %>
              <% end %>
            </td>

          </tr>

        </tbody>

        <% end %>

      </table>

    </div>

    <br>

    <div class="col-xs-4">

      <div>
        <p>
          <strong class="col-xs-3">商品合計</strong>
           ¥<%= (@order.total_payment - @order.shipping_cost).to_s(:delimited)%>
        </p>
      </div>
      <br>

      <div>
        <p>
          <strong class="col-xs-2">送料</strong>
          ¥<%= @order.shipping_cost %>
        </p>
      </div>
      <br>

      <div>
        <p>
          <strong class="col-xs-4">請求金額合計</strong>
          ¥<%= @order.total_payment.to_s(:delimited) %>
        </p>
      </div>
      <br>

    </div>

  </div>

  </div>

</div>