config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  namespace :public do
    get 'homes/top' => 'homes#top', as: 'top'
    get 'homes/about' => 'homes#about', as: 'about'
    root to: 'homes#top'
  end

  namespace :public do
    resources :items, only: [:index,:show]
  end

  namespace :public do
    resources :customers, only: [:update,:edit]
    get 'customers/my_page' => 'customers#show', as: 'customers'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw/:id' => 'customers#withdraw', as: 'withdraw'
  end

  namespace :public do
    resources :cart_items, only: [:index,:update,:destroy,:create]
    delete 'cart_items/destroy_all/:id' => 'cart_items#destroy_all', as: 'destroy_all'
  end

  namespace :public do
    resources :orders, only: [:new,:index,:show,:create]
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get '/thanks' => 'orders#thanks', as: 'thanks'
  end

  namespace :public do
    resources :addresses, only: [:index,:edit,:create,:update,:destroy]
  end

  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  namespace :admin do
    resources :genres, only: [:index,:create,:edit,:update]
  end

  namespace :admin do
    resources :items, only: [:index,:new,:create,:show,:edit,:update]
  end

  namespace :admin do
    resources :customers, only: [:index,:create,:edit,:update,:show]
  end

  namespace :admin do
   resources :orders, only: [:show,:update,:index]
   resources :order_details, only: [:update]
  end

  namespace :admin do
    get "homes/top"
  end

  root to: "homes#top"

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer

  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end

  def self.cart_items_total_payment(cart_items)
    array = []
    cart_items.each do |cart_item|
      array << cart_item.item.price * cart_item.amount
    end
    return (array.sum * 1.1).floor
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :orders, dependent: :destroy

  validates :name, presence: true


end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details

  validates :is_active, inclusion: {in: [true, false]}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済み:4}

  belongs_to :customer
  has_many :order_details
  has_many :items, through: :order_details

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum maiking_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3}


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    # binding.pry
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :configure_permitted_parameters, if: :devise_controller?

  # # def after_sign_in_path_for(resource)
  # #   root_path
  # # end



  # # def after_sign_out_path_for(resource)
  # #   root_path
  # # end


  # protected

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:telephone_number])
  # end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>

      <nav class="navbar navbar-expand-lg navbar-light bg-info">

        <div class="container">

          <% if customer_signed_in? %>
            <strong><%= link_to "NaganoCake", public_root_path, class:"navbar-brand" %></strong>
          <% else %>
            <strong><%= link_to "NaganoCake", root_path, class:"navbar-brand" %></strong>
          <% end %>


          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">

            <span class="navbar-toggler-icon"></span>

          </button>

          <div class="navbar-collapse collapse show" id="navbarNavDropdown" style="">

            <ul class="navbar-nav ml-auto">

              <% if customer_signed_in? %>

                <li class="customer-name">
                 <strong>ようこそ、<%= current_customer.first_name %>さん！</strong>
                </li>


                <li>
                  <%= link_to public_customers_path(current_customer.id), class:'nav-link text-light' do  %>
                    マイページ
                  <% end %>
                </li>

                <li>
                  <%= link_to public_items_path, class:'nav-link text-light' do  %>
                    商品一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to public_cart_items_path, class:'nav-link text-light' do  %>
                    カート
                  <% end %>
                </li>

                <li>
                  <%= link_to public_orders_path, class:'nav-link text-light' do  %>
                    注文履歴一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to public_addresses_path, class:'nav-link text-light' do  %>
                    配送先一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to destroy_customer_session_path, class:'nav-link text-light', method: :delete do  %>
                    ログアウト
                  <% end %>
                </li>

              <% elsif admin_signed_in? %>

                <li>
                  <%= link_to admin_items_path, class:'nav-link text-light' do  %>
                    商品一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to admin_customers_path, class:'nav-link text-light' do  %>
                    会員一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to admin_orders_path, class:'nav-link text-light' do  %>
                    注文履歴一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to admin_genres_path, class:'nav-link text-light' do  %>
                    ジャンル一覧
                  <% end %>
                </li>

                <li>
                  <%= link_to destroy_admin_session_path, class:'nav-link text-light',method: :delete  do  %>
                    ログアウト
                  <% end %>
                </li>

              <% else %>

                <li>
                  <%= link_to new_customer_registration_path, class:'nav-link text-light' do  %>
                    会員登録
                  <% end %>
                </li>

                <li>
                  <%= link_to new_customer_session_path, class:'nav-link text-light' do  %>
                    会員ログイン
                  <% end %>
                </li>

                <li>
                  <%= link_to public_items_path, class:'nav-link text-light' do  %>
                    商品一覧
                  <% end %>
                </li>

              <% end %>

            </ul>

          </div>

        </div>

      </nav>

    </header>

    <%= yield %>

  </body>

</html>